version: '3.3'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: flaskapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://flaskuser:secret@db:5432/flaskapi
    depends_on:
      - db

volumes:
  pgdata:
